# Generated by Django 3.0.5 on 2021-03-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='textarea',
            field=models.TextField(),
        ),
    ]
